language: go

jdk:
  - oraclejdk8
#  - oraclejdk7
#  - openjdk7
#  - openjdk6

sudo: false

# The latest Groovy must be installed because the Groovy version installed by default for `language: groovy` is too old.
install:
  - curl -s get.gvmtool.net | bash
  - echo "gvm_auto_answer=true" > ~/.gvm/etc/config
  - source ~/.gvm/bin/gvm-init.sh
  - gvm install groovy

before_script:
  - $GROOVY_HOME/bin/groovy -version

script:
    - ./gradlew clean check distLocalBin

after_failure:
    - find build/test-results -name "*.xml" | xargs cat

cache:
  directories:
    - $HOME/.gradle
      #- $HOME/.gvm/groovy
